# ----------------------------------
# Pterodactyl Wine Dockerfile
# Environment: Ubuntu 20.04
# Minimum Panel Version: 1.0.0
# ----------------------------------
FROM ubuntu:focal

LABEL maintainer="draakoor <dominique@wellisch-itservice.de>"

ENV WINEDEBUG=fixme-all
ENV WINEARCH=win64
ENV WINEPREFIX=/home/container/.wine

COPY installwine.sh /installwine.sh
RUN chmod +x /installwine.sh 
RUN /installwine.sh && rm /installwine.sh

RUN adduser --disabled-password --gecos "" --home /home/container container
USER container
ENV  USER=container HOME=/home/container

WORKDIR /home/container

COPY entrypoint.sh /entrypoint.sh

ENV DISPLAY=:0

ENV WINEPATH=/iw4x-base
ENV BASE_FILES=/iw4x-base
ENV IW4x_INSTALL=/home/container

CMD ["/bin/bash", "/entrypoint.sh"]
