FROM mcr.microsoft.com/dotnet/aspnet:10.0

MAINTAINER draakoor, <dominique@wellisch-itservice.de>
WORKDIR /home/container/Lib

# Copy over entrypoint
COPY ./entrypoint.sh /entrypoint.sh
CMD	["/bin/bash", "/entrypoint.sh"]
